site_name: Docs Blog
site_description: Моя документация и заметки
site_author: Ваш никнейм

theme:
  name: material
  palette: 
    primary: indigo
    accent: blue

nav:
  - Главная: index.md
  - Заметки: posts/index.md
  - О блоге: about.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
